"""CPU-only reproduction attempt for the concurrency=64 scheduler starvation
found on real H100 hardware (SESSION_HANDOFF_2026-08-25.md: "12/64 real HTTP
requests failed to make progress within a generous 600s timeout while the
other 52 completed normally -- not a timeout misconfig, genuine uneven
scheduling under load").

WHY THIS IS CPU-TESTABLE AT ALL: engine/scheduler.py's Scheduler.schedule()
and engine/block_manager.py's BlockManager never touch a GPU tensor or call
into the model -- they only manipulate Sequence bookkeeping (token counts,
block tables) and a pure-Python block free-list. Every real forward pass is
driven by a SEPARATE call the real LLMEngine makes after schedule() returns;
this script fakes that part (just appends a dummy token id) so the actual
scheduling/eviction ALGORITHM can be driven to completion in a tight loop,
with no CUDA, no model, no triton import at all.

HYPOTHESIS BEING TESTED: engine/scheduler.py's decode-loop eviction policy
(lines ~139-154) always frees blocks by evicting from the TAIL of
self.running (`self.running.pop()`) to satisfy the sequence at the HEAD
(`self.running.popleft()`), and a preempted sequence is re-admitted from
`self.waiting` at the FRONT (`waiting.appendleft` in preempt()) but re-enters
`self.running` at the BACK (`self.running.append(seq)` in the prefill
branch of schedule()). That combination means a sequence that gets preempted
once lands right back in the eviction-priority position (tail of running),
making it disproportionately likely to be preempted AGAIN before finishing
its (now-redone-from-scratch, since preempt() zeroes num_cached_tokens)
prefill -- a convoy/thrashing effect that could starve a small, unlucky
subset of sequences indefinitely while the majority (never preempted, or
preempted rarely) complete normally. This would reproduce the real bug's
qualitative shape ("most finish, a specific minority never progress") as a
pure scheduling-logic bug, not a GPU/driver/timeout artifact -- meaning it's
fixable without ever touching a GPU.

This is a hypothesis test, not a fix: it EITHER reproduces genuine
starvation (some sequences preempted far more than others and/or never
finish within a generous round budget) at a plausible KV-cache tightness, OR
it doesn't, in which case the real bug is more likely GPU/driver/timing
specific and this rules out the pure-scheduling-logic theory before spending
GPU time re-chasing it there.

Usage:
    python tests/diag_scheduler_starvation_cpu.py
"""
import os
import statistics
import sys
import types

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if "nanovllm" not in sys.modules:
    nanovllm_pkg = types.ModuleType("nanovllm")
    nanovllm_pkg.__path__ = [ROOT]
    nanovllm_pkg.__file__ = os.path.join(ROOT, "__init__.py")
    sys.modules["nanovllm"] = nanovllm_pkg

from nanovllm.engine.scheduler import Scheduler          # noqa: E402
from nanovllm.engine.sequence import Sequence, SequenceStatus  # noqa: E402
from nanovllm.sampling_params import SamplingParams        # noqa: E402


class _FakeConfig:
    """Only the fields Scheduler.__init__ actually reads (see that file) --
    not the real nanovllm.config.Config, which requires a real hf_config /
    checkpoint dir to construct. state_manager=None is passed explicitly at
    Scheduler construction below, so the hybrid-model StateManager path
    (irrelevant to this pure block-eviction hypothesis) never engages."""
    def __init__(self, max_num_seqs, max_num_batched_tokens, num_kvcache_blocks, kvcache_block_size):
        self.max_num_seqs = max_num_seqs
        self.max_num_batched_tokens = max_num_batched_tokens
        self.num_kvcache_blocks = num_kvcache_blocks
        self.kvcache_block_size = kvcache_block_size
        self.eos = -1  # never naturally generated by this script's fake token id
        self.debug_print_preemptions = False


def run_one_wave(num_seqs, prompt_len, max_tokens, num_kvcache_blocks,
                  max_num_batched_tokens, max_rounds):
    """Simulate ONE 'fire N requests at once' wave (bench_http_concurrency.py's
    own terminology) through the real Scheduler, faking only the token-
    generation step. Returns per-sequence round-admitted/round-finished/
    preempt-count stats plus whether the round budget was exhausted with
    sequences still unfinished (the CPU analog of the real 600s timeout)."""
    block_size = Sequence.block_size  # 256, hardcoded on Sequence -- see that class
    config = _FakeConfig(num_seqs, max_num_batched_tokens, num_kvcache_blocks, block_size)
    scheduler = Scheduler(config, state_manager=None, model_runner=None, tokenizer=None)

    sp = SamplingParams(temperature=0.0, max_tokens=max_tokens, ignore_eos=True)
    seqs = []
    for _ in range(num_seqs):
        seq = Sequence([1] * prompt_len, sp)  # token id value is irrelevant here
        scheduler.add(seq)
        seqs.append(seq)

    preempt_counts = {s.seq_id: 0 for s in seqs}
    admitted_round = {s.seq_id: None for s in seqs}
    finished_round = {s.seq_id: None for s in seqs}
    # Track preemptions by wrapping Scheduler.preempt via monkeypatch-free
    # counting: a sequence's status flips RUNNING->WAITING only inside
    # preempt(), so diff running-set membership round over round instead of
    # patching the method -- keeps this a black-box drive of real scheduler
    # code, not an instrumented copy of it.
    prev_running_ids = set()

    round_i = 0
    while not scheduler.is_finished() and round_i < max_rounds:
        round_i += 1
        running_ids_before = {s.seq_id for s in scheduler.running}
        scheduled_seqs, is_prefill = scheduler.schedule()
        # Anyone who WAS running last round but is no longer in
        # scheduler.running NOR in scheduled_seqs (and isn't finished) just
        # got preempted this round.
        now_running_ids = {s.seq_id for s in scheduler.running} | {s.seq_id for s in scheduled_seqs}
        dropped = prev_running_ids - now_running_ids
        for sid in dropped:
            preempt_counts[sid] += 1
        prev_running_ids = {s.seq_id for s in scheduled_seqs} if not is_prefill else prev_running_ids

        for seq in scheduled_seqs:
            if admitted_round[seq.seq_id] is None and seq.status == SequenceStatus.RUNNING:
                admitted_round[seq.seq_id] = round_i
            if not is_prefill:
                prev_running_ids.add(seq.seq_id)

        fake_token = 42  # never equals config.eos (-1); ignore_eos=True anyway
        token_ids = [fake_token] * len(scheduled_seqs)
        scheduler.postprocess(scheduled_seqs, token_ids, is_prefill)

        for seq in scheduled_seqs:
            if seq.is_finished and finished_round[seq.seq_id] is None:
                finished_round[seq.seq_id] = round_i

    unfinished = [s.seq_id for s in seqs if finished_round[s.seq_id] is None]
    return {
        "rounds_used": round_i,
        "hit_round_cap": round_i >= max_rounds and bool(unfinished),
        "num_unfinished": len(unfinished),
        "unfinished_ids": unfinished,
        "preempt_counts": preempt_counts,
        "admitted_round": admitted_round,
        "finished_round": finished_round,
    }


def main():
    NUM_SEQS = 64
    PROMPT_LEN = 1024
    MAX_TOKENS = 1024
    # Generous, matches "cheap fix" theory being tested SEPARATELY -- this
    # script isolates the KV-cache/eviction axis, not the batched-token-
    # budget axis, so keep this large enough to never be the bottleneck here.
    MAX_BATCHED_TOKENS = 262144
    MAX_ROUNDS = 20000

    print(f"Config: num_seqs={NUM_SEQS} prompt_len={PROMPT_LEN} max_tokens={MAX_TOKENS} "
          f"block_size={Sequence.block_size} max_rounds={MAX_ROUNDS}")
    print("Sweeping num_kvcache_blocks from tight to generous (each seq needs up to "
          f"{-(-(PROMPT_LEN + MAX_TOKENS) // Sequence.block_size)} blocks at full length; "
          f"{NUM_SEQS} seqs need up to "
          f"{NUM_SEQS * -(-(PROMPT_LEN + MAX_TOKENS) // Sequence.block_size)} blocks with zero contention)\n")

    for num_blocks in [80, 120, 160, 200, 260, 320, 400, 600]:
        result = run_one_wave(NUM_SEQS, PROMPT_LEN, MAX_TOKENS, num_blocks,
                               MAX_BATCHED_TOKENS, MAX_ROUNDS)
        counts = list(result["preempt_counts"].values())
        never_preempted = sum(1 for c in counts if c == 0)
        heavily_preempted = sum(1 for c in counts if c >= 5)
        max_preempt = max(counts)
        status = "STARVED" if result["num_unfinished"] else "all finished"
        print(f"num_kvcache_blocks={num_blocks:4d}  rounds={result['rounds_used']:6d}  "
              f"unfinished={result['num_unfinished']:2d}/{NUM_SEQS}  {status:14s}  "
              f"preempts: never={never_preempted:2d} heavy(>=5)={heavily_preempted:2d} max={max_preempt:3d}")
        if result["num_unfinished"]:
            stuck_preempts = [result["preempt_counts"][sid] for sid in result["unfinished_ids"]]
            finished_preempts = [c for sid, c in result["preempt_counts"].items()
                                  if sid not in result["unfinished_ids"]]
            print(f"    -> stuck seqs' preempt counts: {sorted(stuck_preempts, reverse=True)[:15]}"
                  f"{'...' if len(stuck_preempts) > 15 else ''}")
            if finished_preempts:
                print(f"    -> finished seqs' preempt counts: mean={statistics.mean(finished_preempts):.2f} "
                      f"max={max(finished_preempts)}")

    print("\nInterpretation: if some tightness level shows 'unfinished > 0' together with "
          "stuck sequences' preempt counts sharply higher than finished sequences' -- that IS "
          "the convoy/thrashing pattern this script hypothesized, reproduced entirely on CPU, "
          "no GPU or timing artifact involved. If every level either finishes everyone or stalls "
          "ALL sequences equally (not a specific minority), the real starvation is more likely "
          "GPU/driver/timing-specific and NOT this scheduling-logic bug.")

    print("\n" + "=" * 78)
    print("SECOND HYPOTHESIS: not eviction thrashing, but a low max_num_seqs simply "
          "queuing the tail of a 64-wide wave behind a much smaller real batch cap "
          "(the --max-num-seqs / --max-num-batched-tokens theory from the same "
          "session, applied here to the concurrency=64 case specifically) -- with "
          "GENEROUS KV cache (so this isolates max_num_seqs alone), does capping it "
          "well below 64 leave a clean, ORDERED tail of later-arriving sequences "
          "still unfinished at a round budget standing in for the real 600s wall-clock "
          "timeout, rather than a scattered subset?")
    print()
    GENEROUS_BLOCKS = 4096
    # Round budget standing in for "600s of real wall-clock decode": at
    # max_num_seqs=8 the earlier all-64 sweep above needed ~1500-4600 rounds
    # (1 round == roughly 1 decode step across the active batch) to fully
    # drain 64 sequences at max_num_seqs=64 with real concurrency; capping
    # max_num_seqs to 8 means 8x fewer sequences decode per round, so this
    # uses a round budget scaled the same way rather than an arbitrary guess.
    ROUND_BUDGET = 3000
    for cap in [4, 8, 16, 32, 64]:
        config = _FakeConfig(cap, MAX_BATCHED_TOKENS, GENEROUS_BLOCKS, Sequence.block_size)
        scheduler = Scheduler(config, state_manager=None, model_runner=None, tokenizer=None)
        sp = SamplingParams(temperature=0.0, max_tokens=MAX_TOKENS, ignore_eos=True)
        seqs = [Sequence([1] * PROMPT_LEN, sp) for _ in range(NUM_SEQS)]
        arrival_order = {s.seq_id: i for i, s in enumerate(seqs)}
        for s in seqs:
            scheduler.add(s)

        r = 0
        while not scheduler.is_finished() and r < ROUND_BUDGET:
            r += 1
            scheduled_seqs, is_prefill = scheduler.schedule()
            scheduler.postprocess(scheduled_seqs, [42] * len(scheduled_seqs), is_prefill)

        unfinished = [s for s in seqs if not s.is_finished]
        unfinished_arrival_idx = sorted(arrival_order[s.seq_id] for s in unfinished)
        is_clean_tail = (
            not unfinished_arrival_idx
            or unfinished_arrival_idx == list(range(NUM_SEQS - len(unfinished), NUM_SEQS))
        )
        print(f"max_num_seqs={cap:3d}  rounds_used={r:5d}  unfinished={len(unfinished):2d}/{NUM_SEQS}  "
              f"clean_ordered_tail={is_clean_tail}  "
              f"unfinished_arrival_indices={unfinished_arrival_idx[:10]}"
              f"{'...' if len(unfinished_arrival_idx) > 10 else ''}")

    print("\nInterpretation: 'clean_ordered_tail=True' with unfinished>0 means the "
          "sequences still stuck at the round budget are EXACTLY the last-arriving "
          "ones in FCFS order -- a queuing delay from an undersized max_num_seqs, not "
          "an eviction/thrashing bug and not GPU-specific. That would mean the SAME "
          "fix already proposed for the flat throughput curve (raise --max-num-seqs / "
          "--max-num-batched-tokens to match target concurrency) is also the fix for "
          "the concurrency=64 'starvation' -- it likely isn't starvation at all, just "
          "requests that hadn't reached the front of the queue yet when the 600s "
          "timeout fired.")


if __name__ == "__main__":
    main()
